### ISSUE TITLE
JavaScript hide fails when using multiple @HIDE_BY_ROLE fields

### ISSUE THREAD

**Issue by steentje34** [denshade/redcap_hidden_by_role#1]
When using multiple @HIDE_BY_ROLE fields, only the last @HIDE_BY_ROLE field in the project gets hidden for users who are not supposed to see the field. It seems that the issue is linked to following line.
https://github.com/denshade/redcap_hidden_by_role/blob/cff8187eed15f9c4961f0efaeb25b77045051fb6/HideByRoleClass.php#L87

Adding a semicolon should solve the issue.
`echo 'UZG_hideaway.hideIt("' . $fieldToHide . '");'; `

**Comment by denshade** [comment]
This problem should be resolved.
